# Generated by Django 5.1.1 on 2024-10-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimatiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
