# Generated by Django 5.1.1 on 2024-11-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimatiApp', '0002_correocontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
