# Generated by Django 5.1.1 on 2025-06-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimatiApp', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='Deshabilitado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
