# Generated by Django 5.1.1 on 2025-06-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimatiApp', '0005_carrito_deshabilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
