# Generated by Django 5.1.1 on 2025-07-20 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimatiApp', '0007_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AnimatiApp.carrito'),
        ),
    ]
