# Generated by Django 5.1.1 on 2025-08-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimatiApp', '0008_pedido_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
